### ISSUE TITLE
Sign without initialized KeyPair uses incorrect curve parameters 

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neo-python-core#176]
* neo-python-core version: 0.5.7-dev
* Python version: 3.6.3
* Operating System: OSX

### Description
As described by user *Vinc* in Discord, the following code demonstrates two different results for Sign/Verify using the same input and private key:
```
from neocore.Cryptography.Crypto import Crypto
from neocore.KeyPair import KeyPair
import binascii

message = binascii.hexlify(b'Hello World')
signature = Crypto.Sign(message, '8631cd2635c416ba5f043561e9d2ff40b79c3bb2eb245e176615298b8372d0a4')
key = KeyPair(bytes.fromhex('8631cd2635c416ba5f043561e9d2ff40b79c3bb2eb245e176615298b8372d0a4'))

print(signature.hex())
print(Crypto.VerifySignature(message, signature, key.PublicKey, unhex = True))


message = binascii.hexlify(b'Hello World')
key = KeyPair(bytes.fromhex('8631cd2635c416ba5f043561e9d2ff40b79c3bb2eb245e176615298b8372d0a4'))
signature = Crypto.Sign(message, '8631cd2635c416ba5f043561e9d2ff40b79c3bb2eb245e176615298b8372d0a4')

print(signature.hex())
print(Crypto.VerifySignature(message, signature, key.PublicKey, unhex = True))
```
The only difference in the two tests is that in the first test, `Sign` is called before `KeyPair`, and it returns `False` when time for verification. The second test, with `KeyPair` called before `Sign`, returns `True`.

This is related to the `Sign` function not initializing the bitcoin library with the secp256r1 curve values as the initialization in `KeyPair` does. So the first test actually signs the data with secp256k1, the default for the `bitcoin` library.

I recommend adding code to initialize the bitcoin library with secp256r1 curve values in `Sign` (and any other operation that could be called where a private key could be passed in directly instead of as part of an already-initialized `KeyPair` object.

**Comment by ixje** [comment]
fix by #177
