### ISSUE TITLE
[Brainstorm] what Cryptography Helper functions do we want/need?

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python-core#20]
### Description
The purpose of this issue is to brainstorm and collect what functions are useful to have as helper methods for cryptography related operations. Some of these might already be present, which is fine since we're trying to collect an overview.

- public key (ECPoint or bytes) to redeem script
- public key to script hash
- public key to public address
- redeem script to script hash
- redeem script to public address
- script hash to public address
- signature to public address
- WIF to public address
- WIF to script hash
- WIF to private key
- private key to WIF
- double SHA256 (convenience wrapper)

**Crypto related, not necessarily as helper?**
Some of these are arguably better suited to run/implement in KeyPair. Opening the discussion here to see if e.g. convenience wrappers should be provided.
 
- isValidWIF
- isValidPublicAddress
- encrypt WIF (NEP2)
- decrypt WIF (NEP2)

**Comment by metachris** [comment]
Looks to me like all of those would be a good fit for neocore.

cc/ @localhuman
