### ISSUE TITLE
[Brainstorm] What kind of data type conversions and other utilities do we want in the cli tool?

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python-core#39]
Currently:

* Address to ScriptHash (see #40)

What else? :)

**Comment by brianlenz** [comment]
Here are a few utilities that might be useful based on questions I've seen come up in Discord:

- Script hash to address can also be useful (reverse of above)
```
base58.b58encode_check(b'\x17' + val)
```
- Byte array string to int conversion:
```
int.from_bytes(val, "little")
```
- Hex string to int conversion:
```
int.from_bytes(bytearray.fromhex(val),"little")
```
- Hex encode byte array string
```
binascii.hexlify(val)
```

**Comment by metachris** [comment]
Great suggestions!

Been playing with it, but how do you pass `b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9'` as cli argument? With the quotes and double-quotes it's hard.

All this is almost better suited for a web-frontend perhaps?

**Comment by brianlenz** [comment]
Agreed that a web front-end would probably be better. It would likely solve the CLI parameter issue you are describing.

To pass the parameter, using something like the Prompt parser, I think you can do `bytearray(b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9')`.
