### ISSUE TITLE
Add Python 2 support

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python-core#42]
Currently neocore is only compatible with Python 3, because several of the internal modules do some py3 specific byte transformations.

Could be made compatible with Python 2 with some effort, would be great to have I think, but perhaps not a super priority. All the requirements work already with Python 2.

### How to hack on this

Remove the line that restricts neocore to Python 3: [setup.py#L21](https://github.com/CityOfZion/neo-python-core/blob/master/setup.py#L21)

Then create a venv, install the deps and run the tests

    virtualenv2 venv-py2
    . venv-py2/bin/activate
    pip install -e .
    pip install -r requirements_dev.txt
    python -m unittest discover tests

**Comment by ixje** [comment]
With the latest `Makefile` also testing the latest upstream `neo-python` this is unlikely to ever get a build passing unless we start hacking many things into it there as well. Python 2.x should have EOL'ed in 2014/15 and now will in 2020, so I'd say drop it. It's time to enjoy its life from a memory !

**Comment by metachris** [comment]
Good point, thanks @ixje ! Let's close this, not needed
