### ISSUE TITLE
Bring coverage back to 100% - add tests for cli.py

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python-core#47]
* neo-python-core version: v0.3.11-dev
* Python version: 3.x
* Operating System: osx

### Description

Test coverage dropped to 98% after the addition of `/neocore/bin/cli.py`. We should bring it back to 💯

**Comment by ixje** [comment]
also add a test for this #50

**Comment by jseagrave21** [comment]
@ixje I can see that coverage for neo-python-core is still not at 100% and a large portion of that is due to cli.py. I also noticed there is already a test for cli.py. Is there still a need to add tests for cli.py or update the cli test?

**Comment by ixje** [comment]
@jseagrave21 ideally we cover all code. How to best test the commandline arguments part is something to research, I currently don't have a clear view on that either.
