### ISSUE TITLE
Difference in BigInteger causing fork (neo-python vs neo-cli C#)

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neo-python-core#49]
* neo-python-core version: master
* Python version: 3
* Operating System: Deepin

### Description

I deployed this contract (in C#) and tested storage "size" and "value":
```using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;
namespace NeoContract1
{
    public class Contract1 : SmartContract
    {
        public static int Main()
        {
            Runtime.Notify("oi");
            BigInteger bi = 1;
            Runtime.Notify(bi);
            bi -= 1;
            byte[] ba = bi.ToByteArray();
            Runtime.Notify(ba.Length);
            if(ba.Length > 0)
                Runtime.Notify(ba[0]);
            Storage.Put(Storage.CurrentContext, "size", ba.Length+10);
            Storage.Put(Storage.CurrentContext, "value", ba);
            
            return 3;
        }
    }
}
```

According to Python RPC, "size is 10" (because Bigint 0 to bytearray is empty), but according to C# RPC, "size is 11" (because BigInt 0 in C# is b'\x00', not empty).                                    

### What I Did

I used neocompiler.io Eco platform, that already integrates full neo-python and neo-cli + neo C# ecosystem.
It's easy to change the RPC node (on top of the screen), python is localhost:10332 and C# is localhost:30335 (if doing locally). Online is https://node1.neocompiler.io and https://eco.neocompiler.io (a current workaround for python rpc... will receive a better name in a few days :D)

It's worth mentioning that theses tests are part of the fork competition Vitor and I are promoting at NeoResearch, with the goal of fixing differences in Neo ecosystem modules that could cause future forks in the blockchain.

**Comment by localhuman** [comment]
Thanks for the bug report! We will look into it!

**Comment by igormcoelho** [comment]
This is the reference:
https://referencesource.microsoft.com/#System.Numerics/System/Numerics/BigInteger.cs,285

**Comment by metachris** [comment]
Merged the PR and triggered a new PyPI build. After v0.4.7 is up on PyPI, we need an update to the neo-python dependencies to get this into neo-python. 

https://travis-ci.org/CityOfZion/neo-python-core/builds/385872559

Will close this ticket once neo-python is updated

**Comment by metachris** [comment]
For reference: https://github.com/CityOfZion/neo-python/pull/446
